# 以游子吟服务器为例，当config表增加配置时，均需要在此次配置

INSERT INTO config
  (version, dist, section, name, value, checksum, memo)
VALUES
  ("", "游子吟", "global", "vendue_place", "游子吟一线", "", ""),
  ("", "游子吟", "global", "online_bank_url", "http://account.gyyx.cn/passport/gamepaylogin.aspx", "", ""),
  ("", "游子吟", "global", "mobile_inquiry_url", "http://transfer.gyyx.cn:81/WenDaoServiceV3/WenDao/GameOrderQuery/", "", ""),
  ("", "游子吟", "global", "aa_server", "127.0.0.1:700", "", ""),
  ("", "游子吟", "global", "aa_url", "http://wd.gyyx.cn/data.html", "", ""),
  ("", "游子吟", "global", "gs_cpu_busy", "19", "", ""),
  ("", "游子吟", "global", "gs_user_busy", "70", "", ""),
  ("", "游子吟", "global", "protect_phone", "([\"msg_content\":\"1\",\"msg_no\":\"18954164801\",\"extra_msg\":\"电话密保将于#R2015年5月31日#n停止使用，官方推荐手机乾坤锁，已有IOS和安卓版本，#G#url下载绑定请点击[http://wd.gyyx.cn/huodong/sjqks/xz.html]#t#n。\",\"tip\":\"#R你的账号已经绑定了电话密保，需解除锁定后才能登陆游戏，请拨打电话#Y400-100-1824，400-811-0495#R，如果电话忙请尝试拨打#Y0531-55593321#R解除锁定，也可编辑短信“#Y1#R”发送到#Y18954164801#R解锁。#n\",\"reserver_no\":\"0531-55593321\",\"main_no\":\"400-100-1824，400-811-0495\",])", "", ""),
  ("", "游子吟", "global", "music_enable", "1", "", ""),
  ("", "游子吟", "global", "music", "http://wdmusic.gyyx.cn/", "", ""),
  ("", "游子吟", "global", "mobile_recharge_url", "http://transfer.gyyx.cn:81/WenDaoServiceV3/WenDao/SZFDirectPay/", "", ""),
  ("", "游子吟", "global", "sms_url", "http://800617.com/gyzc/", "", ""),
  ("", "游子吟", "global", "mobile_url", "http://account.gyyx.cn/passport/gamepaylogin.aspx", "", ""),
  ("", "游子吟", "global", "coin_trade_gs", "([\"min_id\":1,\"max_id\":10,])", "", ""),
  ("", "游子吟", "global", "shop_gs", "([\"min_id\":1,\"max_id\":10,])", "", ""),
  ("", "游子吟", "global", "交易平台", "1", "", ""),
  ("", "游子吟", "global", "reduce_server_place", "游子吟六线", "", ""),
  ("", "游子吟", "global", "purchase_gs", "([\"min_id\":1,\"max_id\":10,])", "", ""),
  ("", "游子吟", "global", "stall_gs", "([\"min_id\":1,\"max_id\":10,])", "", ""),
  ("", "游子吟", "global", "stat_gs_log_level", "1", "", ""),
  ("", "游子吟", "global", "wedding_server", "游子吟二线", "", ""),
  ("", "游子吟", "global", "gs_user_over", "99", "", ""),
  ("", "游子吟", "global", "limit_login", "limit_level=0,login_num=5", "", ""),
  ("", "游子吟", "global", "phah_effect_timeout", "30", "", ""),
  ("", "游子吟", "global", "试道大会", "游子吟六线:60-69,70-79,80-89/游子吟七线:90-99,100-109,110-119/游子吟八线:120-129,130-139,140-149,150-159,160-169", "", ""),
  ("", "游子吟", "global", "world_boss_server", "游子吟三线", "", ""),
  ("", "游子吟", "global", "skill_workshop_gs", "([\"min_id\":1,\"max_id\":6,])", "", ""),
  ("", "游子吟", "global", "shenbin_liqi_task", "([ \"start_time\" : \"2014-12-12-00:00:00\", \"end_time\" : \"2015-01-05-00:00:00\"])", "", ""),
  ("", "游子吟", "global", "enable_mobile_client", "1", "", ""),
  ("", "游子吟", "global", "tt_sale_method", "13", "", ""),
  ("", "游子吟", "global", "trade_reservation", "1", "", ""),
  ("", "游子吟", "global", "gs_cpu_full", "90", "", ""),
  ("", "游子吟", "global", "vip_sms_cookie_effect", "600", "", ""),
  ("", "游子吟", "global", "log_error", "([ \"log_servers\" : \"*\", \"log_mode\" : 1, ])", "", ""),
  ("", "游子吟", "global", "gs_user_full", "90", "", ""),
  ("", "游子吟", "global", "WAR_GROUP_A", "游子吟三线", "", ""),
  ("", "游子吟", "global", "WAR_GROUP_B", "游子吟四线", "", ""),
  ("", "游子吟", "global", "WAR_GROUP_C", "游子吟五线", "", ""),
  ("", "游子吟", "global", "maximum_vendue_pet", "1", "", ""),
  ("", "游子吟", "global", "maximum_vendue_item", "1", "", ""),
  ("", "游子吟", "global", "wuzhuangyuan", "游子吟二线:80-89,120-129/游子吟三线:90-99,130-139/游子吟四线:100-109,140-149/游子吟五线:110-119,150-159,160-169", "", ""),
  ("", "游子吟", "global", "maximum_vendue_sys", "11", "", ""),
  ("", "游子吟", "global", "alipay_url", "http://pay.gyyx.cn/alipay/sign", "", ""),
  ("", "游子吟", "global", "alipay_recharge_url", "http://transfer.gyyx.cn:81/WenDaoServiceV3/WenDao/AliDirectPay/", "", ""),
  ("", "游子吟", "global", "vip_sms_url", "http://security.gyyx.cn/SMS/Index/", "", ""),
  ("", "游子吟", "global", "hero_boss_server", "游子吟四线", "", ""),
  ("", "游子吟", "global", "map_decorate_server", "游子吟四线", "", ""),
  ("", "游子吟", "global", "longxue_boss_server", "游子吟二线", "", ""),
  ("", "游子吟", "global", "pantaoyuan_zhengduozhan", "([ 100 : \"游子吟七线\", 110 : \"游子吟七线\", 120 : \"游子吟六线\", 130 : \"游子吟五线\", 140 : \"游子吟四线\", 150 : \"游子吟四线\", 160 : \"游子吟四线\" ])", "", ""),
  ("", "游子吟", "global", "menpai_hubao", "([\"游子吟五线\":\"130-MAX_LEVEL_CEIL\",\"游子吟六线\":\"100-129\",\"游子吟七线\":\"70-99\",\"游子吟八线\":\"40-69\"])", "", ""),
  ("", "游子吟", "global", "menpai_dazhan", "([\"游子吟八线\":({60,79}),\"游子吟七线\":({80,99}),\"游子吟六线\":({100,129}),\"游子吟五线\":({130,MAX_LEVEL_CEIL})])", "", ""),
  ("", "游子吟", "global", "门派比武大会", "游子吟七线:金系/游子吟六线:木系/游子吟二线:水系/游子吟八线:火系/游子吟六线:土系", "", ""),
  ("", "游子吟", "global", "luandou", "游子吟五线", "", ""),
  ("", "游子吟", "global", "challenge_match", "([\"150-169\":\"游子吟四线\",\"140-149\":\"游子吟四线\",\"130-139\":\"游子吟五线\",\"120-129\":\"游子吟五线\",\"110-119\":\"游子吟六线\",\"100-109\":\"游子吟六线\",\"90-99\":\"游子吟七线\",\"80-89\":\"游子吟七线\",\"70-79\":\"游子吟八线\",\"60-69\":\"游子吟八线\"])", "", ""),
  ("", "游子吟", "global", "zhengdou", "游子吟五线", "", ""),
  ("", "游子吟", "global", "baishou_shengyan", "([\"游子吟五线\":({40,79,}),\"游子吟六线\":({80,99,}),\"游子吟七线\":({100,119,}),\"游子吟八线\":({120,MAX_LEVEL_CEIL,}),])", "", ""),
  ("", "游子吟", "global", "lzn_xianzi_cifu", "({\"游子吟五线\",\"游子吟六线\",\"游子吟七线\",\"游子吟八线\"})", "", ""),
  ("", "游子吟", "global", "节节高升", "70 : 游子吟四线/80 : 游子吟四线/90 : 游子吟四线/100 : 游子吟五线/110 : 游子吟五线/120 : 游子吟五线/130 : 游子吟六线/140 : 游子吟六线", "", ""),
  ("", "游子吟", "global", "yuqing_shandian_challenge", "游子吟三线", "", ""),
  ("", "游子吟", "global", "race_server", "游子吟一线,游子吟二线", "", ""),
  ("", "游子吟", "global", "temp_online_mall", "({ ([\"gold_start\" : \"2015-5-8-00:00:00\", \"gold_end\" : \"2015-6-7-23:59:00\", \"names\" :({\"18新服惊喜大礼包\", \"28新服特惠礼包\", \"28新服养育大礼包\", \"32新服助战礼包\", \"48新服镶嵌礼包\", \"108修仙大礼包\", \"168新服镶嵌礼包\", \"168利器大礼包\", \"298神兵大礼包\"}) ]), ([ \"gold_start\" : \"2012-08-12-00:00:00\", \"gold_end\" : \"2012-08-27-23:59:00\", \"names\" : ({ \"180天年费会员卡\", \"360天年费会员卡\" }) ]) })", "", ""),
  ("", "游子吟", "global", "xyhc_server", "游子吟一线,游子吟二线", "", ""),
  ("", "游子吟", "global", "wuxing_zhengba", "({ \"游子吟四线\",\"游子吟五线\" })", "", ""),
  ("", "游子吟", "global", "group_buying_server", "游子吟二线", "", ""),
  ("", "游子吟", "global", "download_url", "http://wdshow.gyyx.cn/", "", ""),
  ("", "游子吟", "global", "upload_page", "askupload/up.php", "", ""),
  ("", "游子吟", "global", "upload_server", "219.234.90.199", "", ""),
  ("", "游子吟", "global", "common_guess_server", "游子吟四线", "", ""),
  ("", "游子吟", "global", "notice_level_up_url", "http://api.activityresult.gyyx.cn/useractivity/activitystate?", "", ""),
  ("", "游子吟", "global", "illegal_tao_punish", "([])", "", ""),
  ("", "游子吟", "global", "fengyin_zhifa", "([\"游子吟三线\": \"40-69\", \"游子吟四线\":\"70-99\", \"游子吟五线\": \"100-119\", \"游子吟六线\": \"120-149\"])", "", ""),
  ("", "游子吟", "global", "xinmlw_servers", "游子吟四线:60-79|游子吟五线:80-99|游子吟六线:100-119|游子吟七线:120-MAX_LEVEL_CEIL", "", ""),
  ("", "游子吟", "global", "bianfang_gaoren", "游子吟四线:60-79/游子吟五线:80-99/游子吟六线:100-119/游子吟七线:120-149", "", ""),
  ("", "游子吟", "global", "152shoudeng_libao", "({\"2015-05-14-00:00:00\", \"2015-05-14-23:59:59\", \"1.56.0511\" })", "", "(NULL)"),
  ("", "游子吟", "global", "shouci_chongzhi", "([ \"start_time\" : \"2015-5-4-00:00:00\", \"end_time\" : \"2015-6-7-23:59:00\"])", "", ""),
  ("", "游子吟", "global", "laobing_busi", "({})", "", ""),
  ("", "游子吟", "global", "finish_register_time", "2013-12-20-11:20:00", "", ""),
  ("", "游子吟", "global", "red_envelope", "([ \"start_time\" : \"2015-04-20-00:00:00\", \"end_time\" : \"2015-04-27-23:59:59\", \"sort_end_time\" : \"2015-04-26-23:59:59\", \"envelope_list\" : ({ ([ \"time\" : \"2015-04-22-20:00:00\",\"coin\" : 2000000,\"amount\" : 2000,]),([ \"time\" : \"2015-04-22-22:00:00\",\"coin\" : 4000000,\"amount\" : 2000,]) }), \"sys_name\" : \"九周年\", \"version\" : 1 ])", "", ""),
  ("", "游子吟", "global", "bbgs_2011", "([\"游子吟四线\":({60,79,}),\"游子吟五线\":({80,99,}),\"游子吟六线\":({100,119,}),\"游子吟七线\":({120,149,}),])", "", ""),
  ("", "游子吟", "global", "夺宝之战", "70 : 游子吟四线/80 : 游子吟四线/90 : 游子吟四线/100 : 游子吟三线/110 : 游子吟三线/120 : 游子吟三线/130 : 游子吟二线/140 : 游子吟二线", "", ""),
  ("", "游子吟", "global", "myzz", "([\"游子吟三线\":({40,59,}),\"游子吟四线\":({60,79,}),\"游子吟五线\":({80,99,}),\"游子吟六线\":({100,119,}),\"游子吟七线\":({120,155,}),])", "", ""),
  ("", "游子吟", "global", "duobao_qibing", "([1:\"游子吟五线\",2:\"游子吟六线\",])", "", ""),
  ("", "游子吟", "global", "douchong_dahui", "游子吟四线", "", ""),
  ("", "游子吟", "global", "fwqbc", "({\"游子吟一线\",\"游子吟二线\",\"游子吟三线\",\"游子吟四线\"})", "", ""),
  ("", "游子吟", "global", "draft_home_account_list", "xuanxiu001,xuanxiu002,xuanxiu003,xuanxiu004", "", ""),
  ("", "游子吟", "global", "lgxy_server", "游子吟四线", "", ""),
  ("", "游子吟", "global", "zhongxian_baoxi", "({\"游子吟五线\",\"游子吟六线\",\"游子吟七线\",\"游子吟八线\"})", "", ""),
  ("", "游子吟", "global", "ymdx_server", "游子吟一线,游子吟二线", "", ""),
  ("", "游子吟", "global", "manage_server", "游子吟一线", "", ""),
  ("", "游子吟", "global", "chengjiu_daren", "({\"2015-01-24-00:00:00\",\"2015-02-24-23:59:59\",\"2015-03-21-23:59:59\"})", "", ""),
  ("", "游子吟", "global", "super_boss_server", "游子吟四线", "", ""),
  ("", "游子吟", "global", "fishing_server", "({\"游子吟一线\",\"游子吟二线\",\"游子吟三线\",\"游子吟四线\"})", "", ""),
  ("", "游子吟", "global", "比武大会", "游子吟三线:60-69,70-79/游子吟四线:80-89,90-99/游子吟五线:100-109,110-119/游子吟六线:120-129,130-139,140-149", "", ""),
  ("", "游子吟", "global", "defense_city", "游子吟五线|游子吟六线|游子吟七线|游子吟八线", "", ""),
  ("", "游子吟", "global", "convenant_info", "游子吟三线,游子吟四线,游子吟五线,游子吟六线", "", ""),
  ("", "游子吟", "global", "party_qkbgz", "([4:\"游子吟四线\",3:\"游子吟五线\",2:\"游子吟六线\",])", "", ""),
  ("", "游子吟", "global", "party_qql", "游子吟四线", "", ""),
  ("", "游子吟", "global", "CITY_WAR_SERVER", "游子吟四线", "", ""),
  ("", "游子吟", "global", "party_sell_servers", "游子吟四线", "", ""),
  ("", "游子吟", "global", "olympic_guess_server", "游子吟四线", "", ""),
  ("", "游子吟", "global", "task_control_server", "游子吟一线", "", ""),
  ("", "游子吟", "global", "xianshou_cifu", "({\"游子吟五线\",\"游子吟六线\",\"游子吟七线\",\"游子吟八线\"})", "", ""),
  ("", "游子吟", "global", "european_cup_guess_server", "游子吟四线", "", ""),
  ("", "游子吟", "global", "xiying_zhounian", "({\"游子吟五线\",\"游子吟六线\",\"游子吟七线\",\"游子吟八线\"})", "", ""),
  ("", "游子吟", "global", "jingbing_jianyue", "游子吟三线", "", ""),
  ("", "游子吟", "global", "dayuebing_2015", "游子吟三线", "", ""),
  ("", "游子吟", "global", "bzn_yaoshou_ruqin", "({\"游子吟五线\",\"游子吟六线\",\"游子吟七线\",\"游子吟八线\"})", "", ""),
  ("", "游子吟", "global", "charge_rate", "60", "", ""),
  ("", "游子吟", "global", "enable_apply_account", "1", "", ""),
  ("", "游子吟", "global", "exchange_count", "500", "", ""),
  ("", "游子吟", "global", "exchange_day", "30", "", ""),
  ("", "游子吟", "global", "low_all", "1", "", ""),
  ("", "游子吟", "global", "low_count", "18", "", ""),
  ("", "游子吟", "global", "low_day", "1", "", ""),
  ("", "游子吟", "global", "notice", "", "", ""),
  ("", "游子吟", "global", "overdraw", "0", "", ""),
  ("", "游子吟", "global", "present_day", "3", "", ""),
  ("", "游子吟", "global", "protect_phone_xx", "([\"msg_content\":\"1\",\"msg_no\":\"18954164801\",\"extra_msg\":\"电话密保将在2014年8月1日后停止使用，推荐您使用手机乾坤锁，从3月1日至5月31日绑定手机乾坤锁可领取丰富大礼，#G#url点此[http://action.gyyx.cn/ReceivePrize/WDPhoneEKey/index.html]#t#n领取奖励。\",\"tip\":\"#R你的账号已经绑定了电话密保，需解除锁定后才能登陆游戏，请拨打电话#Y400-100-1824，400-811-0495#R，如果电话忙请尝试拨打#Y0531-55593321#R解除锁定，也可编辑短信“#Y1#R”发送到#Y18954164801#R解锁。#n\",\"reserver_no\":\"0531-55593321\",\"main_no\":\"400-100-1824，400-811-0495\",])", "", ""),
  ("", "游子吟", "global", "sncbc_open_gs", "({ \"游子吟一线\", \"游子吟二线\", \"游子吟三线\", \"游子吟四线\", \"游子吟五线\", \"游子吟六线\", \"游子吟七线\", \"游子吟八线\" })", "", ""),
  ("", "游子吟", "global", "zhaojiling", "([\"副本任务\":({\"游子吟五线\"}),\"昆仑神镜\":({\"游子吟六线\"})])", "", ""),
  ("", "游子吟", "global", "bobing_pk_servers", "({ \"游子吟一线\", \"游子吟二线\", \"游子吟三线\" })", "", ""),
  ("", "游子吟", "global", "xixunling_server", "游子吟三线", "", ""),
  ("", "游子吟", "global", "chongzhi_fanli", "({\"2014-08-01-00:00:00\",\"2014-08-03-23:59:59\"})", "", ""),
  ("", "游子吟", "global", "custom_package", "([\"start_time\":\"2014-08-01-00:00:00\",\"end_time\":\"2014-08-03-23:59:59\",])", "", ""),
  ("", "游子吟", "global", "year_insider", "1", "", ""),
  ("", "游子吟", "global", "shequ_xuyuan", "({\"2014-12-11-00:00:00\",\"2014-12-12-23:59:59\"})", "", ""),
  ("", "游子吟", "global", "alipay_qr_url", "http://interface.pay.gyyx.cn/v1/game/AliQrcodeGamePay/AliQrcodeDirectPay", "", ""),
  ("", "游子吟", "global", "xiygc_zhenyz", "游子吟六线", "", ""),
  ("", "游子吟", "global", "xiygc_zhenyzb", "([\"40-69\":6,\"70-79\":6,\"80-89\":6,\"90-99\":7,\"100-109\":7,\"110-119\":7,\"120-129\":8,\"130-139\":8,\"140-149\":8,\"150-159\":8,\"160-169\":8])", "", ""),
  ("", "游子吟", "global", "xinfu_wishing", "([\"start_time\":\"2015-05-08-00:00:00\",\"end_time\":\"2015-06-07-23:59:59\",])", "", ""),
  ("", "游子吟", "global", "sys_purchase_gs", "({8})", "", ""),
  ("", "游子吟", "global", "xinfu_chongbang", "([ \"start_time\" : \"2015-01-01-00:00:00\", \"end_time\" : \"2015-01-31-23:59:59\", \"bonus_time\" : \"2015-02-06-23:59:59\", \"order_end_time\" : \"2015-01-10-23:59:59\", \"url\" : \"http://wd.gyyx.cn/huodong/wdxf/tf/bwcx/cbbs/index.html\" ])", "", ""),
  ("", "游子吟", "global", "shengsidou", "0", "", ""),
  ("", "游子吟", "global", "world_level_config", "0", "", "");
  ("", "游子吟", "global", "dongfu_tiaozhan", "游子吟八线", "", "");
